# Generated by Django 4.2.7 on 2026-03-16 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('humidity', models.IntegerField(help_text='Humidity percentage')),
                ('wind_speed', models.FloatField(help_text='Wind speed in km/h')),
                ('weather_code', models.IntegerField(help_text='Open-Meteo weather code')),
                ('weather_description', models.CharField(max_length=100)),
                ('sunrise', models.DateTimeField()),
                ('sunset', models.DateTimeField()),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_cache', to='weather.city')),
            ],
            options={
                'verbose_name': 'Weather Cache',
                'verbose_name_plural': 'Weather Cache',
                'ordering': ['-cached_at'],
                'unique_together': {('city', 'cached_at')},
            },
        ),
    ]
