# Generated by Django 4.2.7 on 2026-03-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathercache',
            name='sunrise',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathercache',
            name='sunset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
